// packages/react/src/InlineRenderer.tsx
import React, { FC, Fragment } from 'react';
import type { Inline, TometComponents } from './types';
import { ElementRenderer } from './ElementRenderer';

interface InlineRendererProps {
  inlines?: Inline[] | null;
  components?: TometComponents;
  macros?: Record<string, string>;
}

export const InlineRenderer: FC<InlineRendererProps> = ({ inlines, components, macros }) => {
  if (!inlines || !Array.isArray(inlines)) return null;

  return (
    <Fragment>
      {inlines.map((inline, index) => {
        if ('Text' in inline) {
          return <Fragment key={index}>{inline.Text.value}</Fragment>;
        }
        if ('type' in inline && inline.type === 'Text') {
          return <Fragment key={index}>{inline.value}</Fragment>;
        }
        if ('type' in inline && inline.type === 'Code') {
          return <code key={index} className="tomet-inline-code">{inline.content}</code>;
        }
        if ('Element' in inline) {
          return (
            <ElementRenderer
              key={index}
              element={inline.Element}
              components={components}
              macros={macros}
              isInline={true}
            />
          );
        }
        if ('type' in inline && inline.type === 'Element' && inline.data) {
          return (
            <ElementRenderer
              key={index}
              element={inline.data}
              components={components}
              macros={macros}
              isInline={true}
            />
          );
        }
        return null;
      })}
    </Fragment>
  );
};

// packages/svelte/src/InlineRenderer.svelte
<script lang="ts">
  import type { Inline, TometSvelteComponents } from './types';
  import ElementRenderer from './ElementRenderer.svelte';

  interface Props {
    inlines?: Inline[] | null;
    components?: TometSvelteComponents;
    macros?: Record<string, string>;
  }

  let { inlines, components, macros }: Props = $props();
</script>

{#if inlines && Array.isArray(inlines)}
  {#each inlines as inline}
    {#if 'Text' in inline}
      {inline.Text.value}
    {:else if 'type' in inline && inline.type === 'Text'}
      {inline.value}
    {:else if 'type' in inline && inline.type === 'Code'}
      <code class="tomet-inline-code">{inline.content}</code>
    {:else if 'Element' in inline}
      <ElementRenderer element={inline.Element} {components} {macros} isInline={true} />
    {:else if 'type' in inline && inline.type === 'Element' && inline.data}
      <ElementRenderer element={inline.data} {components} {macros} isInline={true} />
    {/if}
  {/each}
{/if}
