// packages/svelte/src/Tomet.svelte
<script lang="ts">
  import type { Document, TometProps } from './types';
  import { extractDocumentMacros } from './utils';
  import BlockRenderer from './BlockRenderer.svelte';

  let {
    content,
    ast,
    components,
    class: className = 'tomet-document',
    parse,
  }: TometProps = $props();

  let documentAst: Document | null = $derived.by(() => {
    if (ast) return ast;
    if (content && typeof parse === 'function') {
      try {
        return parse(content);
      } catch (err) {
        console.error('Failed to parse Tomet document:', err);
        return null;
      }
    }
    return null;
  });

  let macros = $derived(extractDocumentMacros(documentAst));
</script>

{#if documentAst && documentAst.blocks && documentAst.blocks.length > 0}
  <article class={className}>
    {#each documentAst.blocks as block}
      <BlockRenderer {block} {components} {macros} />
    {/each}
  </article>
{/if}

// packages/react/src/Tomet.tsx
import React, { FC, useMemo } from 'react';
import type { Document, TometProps } from './types';
import { extractDocumentMacros } from './utils';
import { BlockRenderer } from './BlockRenderer';

export const Tomet: FC<TometProps> = ({
  content,
  ast,
  components,
  className = 'tomet-document',
  parse,
  fallback = null,
}) => {
  const documentAst: Document | null = useMemo(() => {
    if (ast) return ast;
    if (content && typeof parse === 'function') {
      try {
        return parse(content);
      } catch (err) {
        console.error('Failed to parse Tomet document:', err);
        return null;
      }
    }
    return null;
  }, [ast, content, parse]);

  const macros = useMemo(() => extractDocumentMacros(documentAst), [documentAst]);

  if (!documentAst || !documentAst.blocks || documentAst.blocks.length === 0) {
    return fallback ? <>{fallback}</> : null;
  }

  return (
    <article className={className}>
      {documentAst.blocks.map((block, index) => (
        <BlockRenderer key={index} block={block} components={components} macros={macros} />
      ))}
    </article>
  );
};
